tags="china, miners control bitcoin, miners, mining, centralized"
answer="No #Bitcoin is not controlled by China. Neither do miners control #Bitcoin. Please do some research before tweeting FUD"
links=[
  "https://blog.lopp.net/are-chinese-miners-threat-bitcoin/"
]