tags="miners control bitcoin, miners, mining, nodes, centralized, consensus"
answer="Wrong miners don’t control #bitcoin , Nodes control #Bitcoin, Nodes decide what the rules are"
links=[
  "https://youtu.be/fNk7nYxTOyQ?t=393"
]