tags="video, wastes, energy, energy waste, energy consumption, electricity, scorch the earth, boil the oceans"
answer="Indeed #Bitcoin uses a lot of energy, but that's not a bad thing. Check out this video..."
links=[
  "https://www.youtube.com/watch?v=E5gXD40OHcg"
]