tags="energy, wastes, energy waste, energy consumption, electricity, scorch the earth, boil the oceans"
answer="Indeed #Bitcoin uses a lot of energy, but that's not a bad thing. Check out this article..."
links=[
  "https://nakamotoinstitute.org/mempool/bitcoin-does-not-waste-energy/",
  "https://hbr.org/2021/05/how-much-energy-does-bitcoin-actually-consume",
  "https://blog.trezor.io/three-myths-about-bitcoins-energy-consumption-ef613a1f3d5?gi=c24d8988688e",
  "https://docsend.com/view/adwmdeeyfvqwecj2",
  "https://www.upstreamdata.ca/post/natural-gas-venting-how-bitcoin-solved-a-160-year-old-problem",
  "https://bitcoinandenergy.medium.com/bitcoin-mining-and-the-case-for-more-energy-90094ce25fac",
  "https://www.coindesk.com/the-last-word-on-bitcoins-energy-consumption",
  "https://danhedl.medium.com/pow-is-efficient-aa3d442754d3"
]