tags="video, waste, wastes, energy, energywaste, energyconsumption, electricity"
answer="Indeed #Bitcoin uses a lot of energy, but that's not a bad thing. Check out this video..."
links=[
  "https://www.youtube.com/watch?v=E5gXD40OHcg"
]