tags="energy, energy waste, energy consumption, electricity, visa, credit card"
answer="#Bitcoin is both a payment network and currency, you can’t compare it to Visa. And if you would, Bitcoin actually uses less energy than credit cards."
links=[
  "https://hackernoon.com/the-bitcoin-vs-visa-electricity-consumption-fallacy-8cf194987a50",
  "https://bitcoinmagazine.com/culture/the-hidden-costs-of-the-petrodollar",
  "https://medium.com/@nic__carter/on-bitcoin-the-gray-lady-embraces-climate-lysenkoism-a2d31e465ec0"
]