tags="decentralized, dezentralisation, centralization, centralized"
answer="#Bitcoin is bar far the most decentralized form of money we have. Here's why:"
links=[
  "https://www.truthcoin.info/blog/measuring-decentralization/"
]
