tags="quantum, quantumcomputer, quantumcomputers, quantumcomputing"
answer="No #Bitcoin will not be broken by quantum computers. That’s not how this works, please watch this video to educate yourself before spreading more FUD"
links=[
  "https://youtu.be/nUAoOGVT-e4"
]