tags="slow, tps, speed, settlement"
answer="No #Bitcoin is not too slow. It’s actually extremely effective and achieves final settlement faster than the traditional banking system."
links=[
  "https://nakamotoinstitute.org/mempool/bitcoin-is-not-too-slow/",
  "https://medium.com/@nic__carter/its-the-settlement-assurances-stupid-5dcd1c3f4e41",
  "https://www.youtube.com/watch?v=7bOo3zLFhEk",
  "https://www.youtube.com/watch?v=Rt2C3CsLi7k"
]