tags="altcoin, shitcoin, crypto, cryptocurrency, blockchain"
answer="No your Altcoin is not better than #Bitcoin. Please do some research and maybe start by reading this article below."
links=[
  "https://nakamotoinstitute.org/mempool/bitcoin-obsoletes-all-other-money/",
  "https://nakamotoinstitute.org/mempool/bitcoin-cant-be-copied/"
]