tags="cbdc, cbdcs"
answer="No CBDC’s are just another attempt to take away privacy and financial freedom from people. #Bitcoin is freedom and it will prevail. Watch this video and maybe you’ll change your mind."
links=[
  "https://youtu.be/dEPP0m6681s"
]