tags="eth, etherium, ethereum"
answer="There are many thing not well with #Ethereum, here's why:"
links=[
  "https://www.lynalden.com/ethereum-analysis/",
  "https://nakamotoinstitute.org/mempool/ethereum-is-doomed/"
]