tags="pos, proofofstake"
answer="Proof of Stake is not an improvement over Proof of Work. It leads to increased centralization. Here is why:"
links=[
  "https://medium.com/@BobMcElrath/whats-wrong-with-proof-of-stake-77d4f370be15",
  "https://github.com/libbitcoin/libbitcoin-system/wiki/Proof-of-Stake-Fallacy",
  "https://www.truthcoin.info/blog/pow-cheapest/",
  "https://www.truthcoin.info/blog/pow-and-mining",
  "https://hugonguyen.medium.com/proof-of-stake-the-wrong-engineering-mindset-15e641ab65a2",
  "https://hugonguyen.medium.com/work-is-timeless-stake-is-not-554c4450ce18",
  "https://medium.com/stakin/centralization-of-stake-in-pos-f7ccb8f8254",
  "https://www.truthcoin.info/blog/pos-still-pointless/"
]
