tags="tether, usdt"
answer="There is indeed a lot of uncertainty around #tether, but there is no serious evidence of unbacked new issuance artificially inflating the price of #bitcoin."
links=[
  "https://casebitcoin.com/critiques/bitcoin-is-pumped-by-tether",
  "https://danheld.substack.com/p/dont-fear-tether"
]