tags="backed, upheld"
answer="Sorry do more research, #Bitcoin is backed by the only thing that backs any form of money: the credibility of its monetary properties. #Bitcoin is backed by math."
links=[
  "https://nakamotoinstitute.org/mempool/bitcoin-is-not-backed-by-nothing/"
]