tags="deflation, inflation, deflationary"
answer="Bitcoin's deflationary properties make it actually an excellent form of money. Do yourself a favor and read the #Bitcoin Standard before spreading more FUD. If you can’t afford a copy you can download the book here."
links=[
  "https://twitter.com/saifedean/status/1142197167681155073?s=20"
]