tags="money, notmoney, history"
answer="#Bitcoin is an excellent form of money. Study the history of how money came about and what money is and you will understand."
links=[
  "https://nakamotoinstitute.org/shelling-out/",
  "https://saifedean.com/thebitcoinstandard/"
]