tags="sov, volatile"
answer="#Bitcoin is an excellent store of value, zoom out and see how well it appreciated even in value. Volatile things are not necessarily risky, and the reverse is also true."
links=[
  "https://nakamotoinstitute.org/mempool/bitcoin-is-not-too-volatile/"
]