tags="51attack, hashpower, 51percent, 51, 51%, 51%attack"
answer="No nation states will not be able to 51% attack #bitcoin, we are beyond this point that any nation can take on #bitcoin"
links=[
  "https://www.youtube.com/watch?v=ncPyMUfNyVM"
]