tags="environment, environmental, impact, carbon, co2"
answer="#Bitcoin's energy use is grossly misunderstood by many. Here's why its energy demands are a profoundly positive thing for the planet."
links=[
  "https://www.notion.so/Will-Bitcoin-Scorch-The-Earth-625836f3c5a44af78523f40d2838ae04",
  "https://hassmccook.medium.com/comparing-bitcoins-environmental-impact-f56b18014f64"
]