tags="crime, criminals, criminal, ransomware, ransom, hacker, hackers, theft, thug, thugs"
answer="No #Bitcoin is a transparent ledger anyone can see which is poor for crime."
links=[
  "https://www.forbes.com/sites/haileylennon/2021/01/19/the-false-narrative-of-bitcoins-role-in-illicit-activity/"
]