tags="pyramid, ponzi, scheme"
answer="So you think #bitcoin is a Ponzi scheme? Look closer, in fact Bitcoin does not meet the definition of a Ponzi scheme in any sense,"
links=[
  "https://nakamotoinstitute.org/mempool/bitcoin-is-not-a-pyramid-scheme/",
  "https://www.lynalden.com/bitcoin-ponzi-scheme/"
]