tags="ban, banning, banned, governments, illegal"
answer="No #Bitcoin cannot be banned by governments. Please educate yourself more before tweeting more FUD nonsense."
links=[
  "https://nakamotoinstitute.org/mempool/bitcoin-cannot-be-banned/",
  "https://quillette.com/2021/02/21/can-governments-stop-bitcoin/",
  "https://unchained-capital.com/blog/bitcoin-is-antifragile/"
]